"use client";
// pages/terms-and-conditions.js
import React from 'react';
import Link from 'next/link';
const TermsAndConditions = () => {
  return (
    <div className="container">
      <div className=" px-4 py-8 md:mx-28 ">
        <h1 className="text-3xl font-bold mb-6">Terms & Conditions</h1>
        <div className="space-y-4 w-fit">
          <p>
          This document is an electronic record in terms of the Information Technology Act, 2000, and rules thereunder as applicable, and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures. 
          </p>
          <p>
          This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011, that require publishing the rules and regulations, privacy policy, and Terms of Use for access or usage of the domain name http://opticalhut.in (“Website”), including the related mobile site and mobile application (hereinafter referred to as “Platform”).
          </p>
          <p>
          The Platform is owned by MAHALAXMI OPTICAL TRADERS, a company incorporated under the Companies Act, 1956, with its registered office at 1172, NEAR BINKHAMBI MANDIR, VEER SAVARKAR MARG, KOLHAPUR, Kolhapur, Maharashtra, 416012 (hereinafter referred to as &quot;Platform Owner&quot;, &quot;we&quot;, &quot;us&quot;, or &quot;our&quot;).
          </p>
          <p>
          Your use of the Platform, services, and tools are governed by the following terms and conditions (&quot;Terms of Use&quot;) as applicable to the Platform, including the applicable policies which are incorporated herein by way of reference. If you transact on the Platform, you shall be subject to the policies that are applicable for such transactions. By mere use of the Platform, you shall be contracting with the Platform Owner, and these terms and conditions, including the policies, constitute your binding obligations with the Platform Owner.
          </p>
          <p>
          These Terms of Use relate to your use of our website, goods (as applicable), or services (as applicable) (collectively, “Services”). Any terms and conditions proposed by you which are in addition to or which conflict with these Terms of Use are expressly rejected by the Platform Owner and shall be of no force or effect. These Terms of Use can be modified at any time without assigning any reason. It is your responsibility to periodically review these Terms of Use to stay informed of updates.
          </p>
          <p>
          For the purpose of these Terms of Use, wherever the context so requires, &quot;you&quot;, &quot;your&quot;, or &quot;user&quot; shall mean any natural or legal person who has agreed to become a user/buyer on the Platform.
          </p>
          <p className="uppercase">
          ACCESSING, BROWSING, OR OTHERWISE USING THE PLATFORM INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE, SO PLEASE READ THEM CAREFULLY BEFORE PROCEEDING.
          </p>
          <div className="space-y-2">
            <p>The use of the Platform and/or availing of our Services is subject to the following Terms of Use:</p>
            <div >
              <span className="text-xl ">1. Accuracy of Information: </span>
              To access and use the Services, you agree to provide true, accurate, and complete information to us during and after registration, and you shall be responsible for all acts done through the use of your registered account on the Platform.
            </div>
            <div >
              <span className="text-xl ">2. No Warranty: </span>
              Neither we nor any third parties provide any warranty or guarantee as to the accuracy, timeliness, performance, completeness, or suitability of the information and materials offered on this website or through the Services for any specific purpose. You acknowledge that such information and materials may contain inaccuracies or errors, and we expressly exclude liability for any such inaccuracies or errors to the fullest extent permitted by law.
            </div>
            <div >
              <span className="text-xl ">3. At Your Own Risk: </span>
              Your use of our Services and the Platform is solely and entirely at your own risk and discretion, for which we shall not be liable to you in any manner. You are required to independently assess and ensure that the Services meet your requirements.
            </div>
            <div >
              <span className="text-xl ">4. Intellectual Property: </span>
              The contents of the Platform and the Services are proprietary to us and licensed to us. You will not have any authority to claim any intellectual property rights, title, or interest in its contents. The content includes, but is not limited to, the design, layout, look, and graphics.
            </div>
            <div >
              <span className="text-xl ">5. Unauthorized Use: </span>
              You acknowledge that unauthorized use of the Platform and/or the Services may lead to action against you as per these Terms of Use and/or applicable laws.
            </div>
            <div >
              <span className="text-xl ">6. Service Charges: </span>
              You agree to pay us the charges associated with availing the Services.
            </div>
            <div >
              <span className="text-xl ">7. Lawful Use: </span>
              You agree not to use the Platform and/or Services for any purpose that is unlawful, illegal, or forbidden by these Terms, or by Indian or local laws that might apply to you.
            </div>
            <div >
              <span className="text-xl ">8. Third-Party Links: </span>
              You acknowledge that the website and Services may contain links to third-party websites. Upon accessing these links, you will be governed by the terms of use, privacy policy, and other policies of such third-party websites. These links are provided for your convenience to provide further information.
            </div>
            <div >
              <span className="text-xl ">9. Legally Binding Contract: </span>
              You understand that upon initiating a transaction for availing the Services, you are entering into a legally binding and enforceable contract with the Platform Owner for the Services.
            </div>
            <div >
              <span className="text-xl ">10. Indemnity: </span>
              You shall indemnify and hold harmless the Platform Owner, its affiliates, group companies (as applicable), and their respective officers, directors, agents, and employees, from any claim or demand, or actions including reasonable attorneys’ fees, made by any third party or penalty imposed due to or arising out of your breach of these Terms of Use, Privacy Policy, and other Policies, or your violation of any law, rules, or regulations or the rights (including infringement of intellectual property rights) of a third party.
            </div>
            <div >
              <span className="text-xl ">11. Limitation of Liability: </span>
              In no event will the Platform Owner be liable for any indirect, consequential, incidental, special, or punitive damages, including without limitation, damages for loss of profits or revenues, business interruption, loss of business opportunities, loss of data, or loss of other economic interests, whether in contract, negligence, tort, or otherwise, arising from the use of or inability to use the Services. However, the Platform Owner&apos;s liability will not exceed the amount paid by you for using the Services giving rise to the cause of action or Rupees One Hundred (Rs. 100), whichever is less.
            </div>
            <div >
              <span className="text-xl ">12. Force Majeure: </span>
              Notwithstanding anything contained in these Terms of Use, the parties shall not be liable for any failure to perform an obligation under these Terms if performance is prevented or delayed by a force majeure event.
            </div>
            <div >
              <span className="text-xl ">13. Governing Law and Jurisdiction: </span>
              These Terms and any dispute or claim relating to them, or their enforceability, shall be governed by and construed in accordance with the laws of India. All disputes arising out of or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts in Kolhapur, Maharashtra
            </div>
            <div >
              <span className="text-xl ">14. Contact Information: </span>
              All concerns or communications relating to these Terms must be communicated to us using the contact information provided on this website.
            </div>
          </div>
        </div>

        {/* <h2 className="text-xl font-semibold mt-6">1. Use of Website</h2>
      <ul className="list-disc ml-6 mt-2">
        <li>You must be at least 18 years old or have parental consent to use our website.</li>
        <li>You agree to provide accurate and complete information during registration or purchase.</li>
        <li>Unauthorized use of this website may give rise to a claim for damages or be a criminal offense.</li>
      </ul>

      <h2 className="text-xl font-semibold mt-6">2. Products and Services</h2>
      <ul className="list-disc ml-6 mt-2">
        <li>All products are subject to availability and may be withdrawn or modified without prior notice.</li>
        <li>We reserve the right to refuse service to anyone for any reason at any time.</li>
        <li>Descriptions, pricing, and availability of products may be subject to changes without notice.</li>
      </ul>

      <h2 className="text-xl font-semibold mt-6">3. Payments</h2>
      <ul className="list-disc ml-6 mt-2">
        <li>All payments must be made at the time of purchase using the accepted payment methods.</li>
        <li>Prices include applicable taxes unless stated otherwise.</li>
        <li>Mahalaxmi Optical Traders is not responsible for payment processing errors caused by third-party services.</li>
      </ul>

      <h2 className="text-xl font-semibold mt-6">4. Limitation of Liability</h2>
      <p className="mt-2">
        Mahalaxmi Optical Traders is not liable for any indirect, incidental, or consequential damages arising from the use of our website or products.
      </p>

      <h2 className="text-xl font-semibold mt-6">5. Intellectual Property</h2>
      <p className="mt-2">
        All content on this website, including text, graphics, logos, and images, is the property of Mahalaxmi Optical Traders and is protected by applicable copyright and trademark laws.
      </p> */}

        {/* <h2 className="text-xl font-semibold mt-6">6. Governing Law</h2>
      <p className="mt-2">
        These terms and conditions are governed by the laws of [Your Country/Region]. Any disputes arising from these terms shall be resolved in the courts of [Your Jurisdiction].
      </p> */}

        {/* <h2 className="text-xl font-semibold mt-6">7. Changes to Terms</h2>
      <p className="mt-2">
        Mahalaxmi Optical Traders reserves the right to update or modify these terms and conditions at any time without prior notice. 
        Continued use of the website after changes constitutes acceptance of the revised terms.
      </p>

      <h2 className="text-xl font-semibold mt-6">8. Contact Information</h2>
      <p className="mt-2">
        If you have any questions about these terms, please contact us at 
        <Link href="mailto:mahalaxmiopticaltraders@gmail.com" className="text-blue-500 underline">mahalaxmiopticaltraders@gmail.com</Link>.
      </p> */}
      </div>
    </div>
  );
};

export default TermsAndConditions;
